* substitute
  Traditionally, the verb substitute is followed by for and means ‘put (someone or something) in place of another,’ as in she substituted the fake vase for the real one. From the late 17th century, substitute has also been used to mean ‘replace (someone or something) with someone or something else,’ as in she substituted the real vase with the fake one. This can be confusing, since the two sentences shown above mean the same thing, yet the object of the verb and the object of the preposition have swapped positions. Despite the potential confusion, the second, newer use is well established, especially in some scientific contexts and in sports ( the top scorer was substituted with almost half an hour still to play), and is now generally regarded as part of standard English.

* plead
  In a court of law, a person can plead guilty or plead not guilty. The phrase plead innocent, although commonly found in general use, is not a technical legal term. Note that one pleads guilty to (not of) an offense, and may be found guilty of an offense. See also usage at innocent.  

* censor, censure
  Both censor and censure are used as both verbs and nouns, but censor means ‘scrutinize, revise, or cut unacceptable parts from (a book, movie, etc.)’ or ‘a person who does this,’ while censure means ‘criticize harshly’ or ‘harsh criticism’: the inmates received their mail only after prison officials had censored all the contents; some senators considered a resolution of censure to express strong disapproval of the president's behavior.  

* scenario
  Strictly, a scenario is ‘an outline of a plot’ or ‘a postulated sequence of events’: the worst-case scenario. It is often used loosely to mean ‘situation,’ as in a nightmare scenario, but this should be avoided in careful writing.

* worthwhile
  The adjective worthwhile is used both attributively (that is, before the noun) and predicatively (that is, when it stands alone and comes after the verb). In both positions, it is always correct as one word ( a worthwhile book; we didn't think it was worthwhile), but when used predicatively, it may also be written as two words: we didn't think it was worth while.