* substitute
  Traditionally, the verb substitute is followed by for and means ‘put (someone or something) in place of another,’ as in she substituted the fake vase for the real one. From the late 17th century, substitute has also been used to mean ‘replace (someone or something) with someone or something else,’ as in she substituted the real vase with the fake one. This can be confusing, since the two sentences shown above mean the same thing, yet the object of the verb and the object of the preposition have swapped positions. Despite the potential confusion, the second, newer use is well established, especially in some scientific contexts and in sports ( the top scorer was substituted with almost half an hour still to play), and is now generally regarded as part of standard English.

* plead
  In a court of law, a person can plead guilty or plead not guilty. The phrase plead innocent, although commonly found in general use, is not a technical legal term. Note that one pleads guilty to (not of) an offense, and may be found guilty of an offense. See also usage at innocent.  

* censor, censure
  Both censor and censure are used as both verbs and nouns, but censor means ‘scrutinize, revise, or cut unacceptable parts from (a book, movie, etc.)’ or ‘a person who does this,’ while censure means ‘criticize harshly’ or ‘harsh criticism’: the inmates received their mail only after prison officials had censored all the contents; some senators considered a resolution of censure to express strong disapproval of the president's behavior.  

* scenario
  Strictly, a scenario is ‘an outline of a plot’ or ‘a postulated sequence of events’: the worst-case scenario. It is often used loosely to mean ‘situation,’ as in a nightmare scenario, but this should be avoided in careful writing.

* worthwhile
  The adjective worthwhile is used both attributively (that is, before the noun) and predicatively (that is, when it stands alone and comes after the verb). In both positions, it is always correct as one word ( a worthwhile book; we didn't think it was worthwhile), but when used predicatively, it may also be written as two words: we didn't think it was worth while.

* busy, assiduous, diligent, engaged, industrious, sedulous
  There are varying degrees of busyness. Busy implies actively and attentively involved in work or a pastime (too busy to come to the phone). It can also be used to describe intensive activity of any kind (a busy intersection; a busy day). Someone who is engaged is also busy, but in a more focused way (engaged in compiling a dictionary). Diligent is used to describe earnest and constant effort, and it often connotes enjoyment of or dedication to what one is doing (diligent efforts to rescue injured animals). To be industrious is to be more focused still, often with a definite goal in mind (an industrious employee working for a promotion). Sedulous also applies to goal-oriented activity, but it suggests more close care and perseverance than industrious does (a sedulous investigation of the accident). The award for concentrated effort goes to the person who is assiduous, which suggests painstaking preoccupation with a specific task (the assiduous student is the one most likely to produce exemplary work).

* journey, excursion, expedition, jaunt, pilgrimage, trip, voyage
  While all of these nouns refer to a course of travel to a particular place, usually for a specific purpose, there is a big difference between a jaunt to the nearest beach and an expedition to the rain forest. While a trip may be either long or short, for business or pleasure, and taken at either a rushed or a leisurely pace (a ski trip; a trip to Europe), a journey suggests that a considerable amount of time and distance will be covered and that the travel will take place over land (a journey into the Australian outback). A long trip by water or through air or space is a voyage (a voyage to the Galapagos Islands; a voyage to Mars), while a short, casual trip for pleasure or recreation is a jaunt (a jaunt to the local shopping mall). Excursion also applies to a brief pleasure trip, usually no more than a day in length, that returns to the place where it began (an afternoon excursion to the zoo). Unlike the rest of these nouns, expedition and pilgrimage apply to journeys that are undertaken for a specific purpose. An expedition is usually made by an organized group or company (a scientific expedition; an expedition to locate new sources of oil), while a pilgrimage is a journey to a place that has religious or emotional significance (the Muslims' annual pilgrimage to Mecca; a pilgrimage to the place where her father died).

* ingenious, ingenuous
  Ingenious and ingenuous are often confused. Ingenious means ‘clever, skillful, resourceful’ ( an ingenious device), while ingenuous means ‘artless, frank’ ( charmed by the ingenuous honesty of the child).

* gullible, callow, credulous, ingenuous, naive, trusting, unsophisticated
  Some people will believe anything. Those who are truly gullible are the easiest to deceive, which is why they so often make fools of themselves. Those who are merely credulous might be a little too quick to believe something, but they usually aren't stupid enough to act on it. Trusting suggests the same willingness to believe (a trusting child), but it isn't necessarily a bad way to be (a person so trusting he completely disarmed his enemies). No one likes to be called naive because it implies a lack of street smarts (she's so naive she'd accept a ride from a stranger), but when applied to things other than people, it can describe a simplicity and absence of artificiality that is quite charming (the naive style in which nineteenth-century American portraits were often painted). Most people would rather be thought of as ingenuous, meaning straightforward and sincere (an ingenuous confession of the truth), because it implies the simplicity of a child without the negative overtones. Callow, however, comes down a little more heavily on the side of immaturity and almost always goes hand-in-hand with youth. Whether young or old, someone who is unsophisticated suffers from a lack of experience.

* used to in questions and negatives
  The construction used to is standard, but difficulties arise with the formation of negatives and questions. Traditionally, used to behaves as a modal verb, so that questions and negatives are formed without the auxiliary verb do, as in it used not to be like that and used she to come here? In modern English, this question form is now regarded as very formal or awkwardly old-fashioned, and the use with do is broadly accepted as standard, as in did she use to come here? Negative constructions with do, on the other hand (as in it didn't use to be like that), although common, are informal and are not generally accepted.
  There is sometimes confusion over whether to use the form used to or use to, which has arisen largely because the pronunciation is the same in both cases. Except in negatives and questions, the correct form is used to: we used to go to the movies all the time (not we use to go to the movies). However, in negatives and questions using the auxiliary verb do, the correct form is use to, because the form of the verb required is the infinitive: I didn't use to like mushrooms (not I didn't used to like mushrooms). See also usage at utilize.

* border, bounds, boundary
  border : 多指国与国之间或两地区的分界处，即分界线附近的边缘部分。
  bounds : 常与boundary换用，指土地边界，但意思不如boundary明确，主要用于抽象事物和文学作品中。
  boundary : 侧重地图上正式标定的、双方遵守的边界，也可指较小行政单位间的界线。

* homonym
  In linguistics, a homonym is, in the strict sense, one of a group of words that share the same spelling and pronunciation but have different meanings. Thus homonyms are simultaneously homographs (words that share the same spelling, regardless of their pronunciation) and homophones (words that share the same pronunciation, regardless of their spelling). The state of being a homonym is called homonymy. Examples of homonyms are the pair stalk (part of a plant) and stalk (follow/harass a person) and the pair left (past tense of leave) and left (opposite of right). A distinction is sometimes made between "true" homonyms, which are unrelated in origin, such as skate (glide on ice) and skate (the fish), and polysemous homonyms, or polysemes, which have a shared origin, such as mouth (of a river) and mouth (of an animal).In non-technical contexts, the term "homonym" may be used (somewhat confusingly) to refer to words that are either homographs or homophones. The words row (propel with oars) and row (argument) and row (a linear arrangement of seating) are considered homographs, while the words read (peruse) and reed (waterside plant) would be considered homophones; under this looser definition, both groups of words represent groups of homonyms.

* egotism, egoism
  The words egoism and egotism are frequently confused, as though interchangeable, but there are distinctions worth noting. Both words derive from Latin ego (‘I’), the first-person singular pronoun. Egotism, the more commonly used term, denotes an excessive sense of self-importance, too-frequent use of the word ‘I,’ and general arrogance and boastfulness. Egoism, a more subtle term, is perhaps best left to ethicists, for whom it denotes a view or theory of moral behavior in which self-interest is the root of moral conduct. An egoist, then, might devote considerable attention to introspection, but could be modest about it, whereas an egotist would have an exaggerated sense of the importance of his or her self-analysis, and would have to tell everyone.

* eminent, imminent, immanent
A trio of frequently confused words is eminent, imminent, and immanent. Eminent means 'outstanding, famous': the book was written by an eminent authority on folk art. Imminent means 'about to happen': people brushed aside the possibility that war was imminent. Immanent, often used in religious or philosophical contexts, means 'inherent': he believed in the immanent unity of nature taught by the Hindus.

* umpire, referee, arbitrator, judge
  Referee、Judge、Umpire都是「裁判」的意思，但judge意思最广，泛指各种场合知中的评判人员。Umpire与referee最常被称为运动场上的裁判，前者多用于仲道裁者本身不需随比赛移动位置，如「羽毛球、游泳、板球、棒球、网球…等」，而后者则得随参赛者在场上移动，如「蓝球、拳击、摔跤、足球…等」。
  Arbitrator来自动词arbitrate。Arbitrator是「内仲裁者」的意思，也就是双方为了要平息争端，或寻求解决之道所嘱托的人。它是一个极正式的容字，常用于商业上、政治上、法律上…等。

* transpire
  The common use of transpire to mean ‘occur, happen’ (I'm going to find out exactly what transpired) is a loose extension of an earlier meaning, ‘come to be known’ (it transpired that Mark had been baptized a Catholic). This loose sense of ‘happen,’ which is now more common in American usage than the sense of ‘come to be known,’ was first recorded in US English toward the end of the 18th century and has been listed in US dictionaries from the 19th century. It is often criticized as jargon, an unnecessarily long word used where occur or happen would do just as well.

* labor, drudgery, grind, toil, travail, work
  Most people have to work for a living, meaning that they have to exert themselves mentally or physically in return for a paycheck. But work is not always performed by humans (a machine that works like a charm). Labor is not only human but usually physical work (the labor required to build a stone wall), although it can also apply to intellectual work of unusual difficulty (the labor involved in writing a symphony). Anyone who has been forced to perform drudgery knows that it is the most unpleasant, uninspiring, and monotonous kind of labor (a forklift that eliminates the drudgery of stacking boxes; the drudgery of compiling a phone book). A grind is even more intense and unrelenting than drudgery, emphasizing work that is performed under pressure in a dehumanizing way (the daily grind of classroom teaching). Toil suggests labor that is prolonged and very tiring (farmers who toil endlessly in the fields), but not necessarily physical (mothers who toil to teach their children manners). Those who travail endure pain, anguish, or suffering (his hours of travail ended in heartbreak).

* millennium
  The spelling of millennium is less difficult if one remembers that it comes ultimately from two Latin words containing double letters: mille, ‘thousand,’ and annum, ‘year.’.

* Hardly . . . than versus hardly . . . when
  the conjunction than is best left to work with comparative adjectives and adverbs ( lovelier than; more quickly than). Consider a construction such as Sheila had hardly recovered from the flu when she lost her beloved beagle: in speech, one might tend to use than as the complement to hardly, but in careful writing, since time is the point, the word to use is when. In a more formal context, however, the idea would be better conveyed: No sooner had Sheila recovered from the flu than she lost her beloved beagle. In this sentence, than does belong because it is the natural conjunction after the comparative adjective sooner.

* protagonist
  The first sense of protagonist, as originally used in connection with ancient Greek drama, is ‘the main character in a play.’ In the early 20th century, a new sense arose meaning ‘a supporter of a cause’: a strenuous protagonist of the new agricultural policy. This new sense probably arose by analogy with antagonist, the pro- in protagonist being interpreted as meaning ‘in favor of.’ In fact, the prot- in protagonist derives from the Greek root meaning ‘first.’ Protagonist is best used in its original dramatic, theatrical sense, not as a synonym for supporter or proponent. Further, because of its basic meaning of ‘leading character,’ such usage as the play's half-dozen protagonists were well cast blurs the word's distinctiveness; characters, instead of protagonists, would be more precise.

* temporary, ephemeral, evanescent, fleeting, transient, transitory
  Things that don't last long are called temporary, which emphasizes a measurable but limited duration (a temporary appointment as chief of staff). Something that is fleeting passes almost instantaneously and cannot be caught or held (a fleeting thought; a fleeting glimpse). Transient also applies to something that lasts or stays only a short time (transient house guests), while transitory refers to something that is destined to pass away or come to an end (the transitory pleasure of eating). Evanescent and ephemeral describe what is even more short-lived. Ephemeral literally means 'lasting for only a single day,' but is often used to describe anything that is slight and perishable (his fame was ephemeral). Evanescent is a more lyrical word for whatever vanishes almost as soon as it appears. In other words, a job might be temporary, an emotion fleeting, a visitor transient, a woman's beauty transitory, and glory ephemeral, but the flash of a bird's wing across the sky would have to be called evanescent.

* scatter, broadcast, diffuse, dispel, disperse, disseminate, dissipate
  If you scatter something, you throw it about in different directions, often using force (the wind scattered leaves around the yard). Disperse implies a scattering that completely breaks up a mass or assemblage and spreads the units far and wide (the crowd dispersed as soon as the storm arrived; the ships were so widely dispersed that they couldn't see each other). To dispel is to scatter or to drive away something that obscures, confuses, or bothers (to dispel her fears), while to diffuse is to lessen the intensity of something by spreading it out over a broader area (the curtains diffused the bright sunlight pouring in the window). Dissipate suggests that something has completely dissolved, disintegrated, or vanished (early-morning mist dissipated by the sun). Broadcast originally meant to scatter seed, but it is also used figuratively to mean make public (the news of the president's defeat was broadcast the next morning). Disseminate also means to publish or make public, but it implies a wider audience and usually a longer duration. You can spend a lifetime disseminating knowledge, in other words, but you would broadcast the news of the birth of your first grandchild.  

* felony, misdemeanor
  The distinction between felonies and misdemeanors usually depends on the penalties or consequences attaching to the crime. In English common law, felony originally comprised those offenses (murder, wounding, arson, rape, and robbery) for which the penalty included forfeiture of land and goods.

* mourn, bemoan, grieve, lament, rue, sorrow
  Not everyone exhibits unhappiness in the same way. Grieve is the strongest of these verbs, implying deep mental anguish or suffering, often endured alone and in silence (she grieved for years over the loss of her baby). Mourn is more formal and often more public; although it implies deep emotion felt over a period of time, that emotion may be more ceremonial than sincere (the people mourned the loss of their leader). Lament comes from a Latin word meaning to wail or weep, and it therefore suggests a vocal or verbal expression of loss (The shrieking women lamented their husbands' deaths). Bemoan also suggests suppressed or inarticulate sounds of grief, often expressing regret or disapproval (to bemoan one's fate). Sorrow combines deep sadness with regret and often pertains to a less tragic loss than grieve or mourn (sorrow over a lost love), while rue has even stronger connotations of regret and repentance (she rued the day she was born).

* discreet, discrete
  The words discrete and discreet are pronounced in the same way and share the same origin but they do not mean the same thing. Discrete means ‘separate,’ as in a finite number of discrete categories, while discreet means ‘careful and circumspect,’ as in you can rely on him to be discreet.

* ought to
  The verb ought is a modal verb, which means that, grammatically, it does not behave like ordinary verbs. In particular, the negative is formed with the word not by itself, without auxiliary verbs such as do or have. Thus the standard construction for the negative is he ought not to go. Note that the preposition to is required in both negative and positive statements: we ought to accept her offer, or we ought not to accept her offer (not we ought accept or we ought not accept). The alternative forms he didn't ought to have gone and he hadn't ought to have gone, formed as if ought were an ordinary verb rather than a modal verb, are not acceptable in formal English. Reserve ought for expressing obligation, duty, or necessity, and use should for expressing suitability or appropriateness.

* beg, beseech, entreat, implore, importune, petition, plead, solicit
  How badly do you want something? You can beg for it, which implies a humble and earnest approach. If you entreat, you're trying to get what you want by ingratiating yourself (she entreated her mother to help her prepare for the exam). To plead involves more urgency (he pleaded with the judge to spare his life) and is usually associated with the legal system (she was advised to plead guilty). Beseech also suggests urgency, as well as an emotional appeal (he beseeched her to tell the truth). Implore is still stronger, suggesting desperation or great distress (the look in his mother's eyes implored him to have mercy). If you really want to get your way, you can importune, which means to beg not only urgently but persistently and to risk making a pest of yourself (he importuned her daily to accept his invitation). Petition suggests an appeal to authority (to petition the government to repeal an unjust law), while solicit suggests petitioning in a courteous, formal way (soliciting financial support for the school carnival).

* tempt, allure, beguile, entice, inveigle, lure, seduce
  When we are under the influence of a powerful attraction, particularly to something that is wrong or unwise, we are tempted. Entice implies that a crafty or skillful person has attracted us by offering a reward or pleasure (she was enticed into joining the group by a personal plea from its handsome leader), while inveigle suggests that we are enticed through the use of deception or cajolery (inveigled into supporting the plan). If someone lures us, it suggests that we have been tempted or influenced for fraudulent or destructive purposes or attracted to something harmful or evil (lured by gang members). Allure may also suggest that we have been deliberately tempted against our will, but the connotations here are often sexual (allured by her dark green eyes). Seduce carries heavy sexual connotations (seduced by an older woman), although it can simply mean prompted to action against our will (seduced by a clever sales pitch). While beguile at one time referred exclusively to the use of deception to lead someone astray, nowadays it can also refer to the use of subtle devices to lead someone on (a local festival designed to beguile the tourists).

* enormity
  Enormity traditionally means ‘the extreme scale or seriousness of something bad or morally wrong,’ as in they were struggling to deal with the enormity of the crime. Today, however, a more neutral sense as a synonym for hugeness or immensity, as in he soon discovered the enormity of the task, is common. Some people regard this use as wrong, arguing that enormity in its original sense meant ‘an extreme wickedness’ and should therefore continue to be used only of contexts in which a negative moral judgment is implied. Nevertheless, the sense of 'great size' is now broadly accepted in standard English, although it generally relates to something difficult, such as a task, challenge, or achievement.  

*  get, acquire, attain, gain, obtain, procure, secure
  Get is a very broad term meaning 'to come into possession of.' You can get something by fetching it (get some groceries), by receiving it (get a birthday gift), by earning it (get interest on a bank loan), or by any of a dozen other familiar means. It is such a common, overused word that many writers try to substitute obtain for it whenever possible, perhaps because it sounds less colloquial. But it can also sound pretentious (all employees were required to obtain an annual physical exam) and should be reserved for contexts where the emphasis is on seeking something out (to obtain blood samples). Acquire often suggests a continued, sustained, or cumulative acquisition (to acquire poise as one matures), but it can also hint at deviousness (to acquire the keys to the safe). Use procure if you want to emphasize the effort involved in bringing something to pass (procure a mediated divorce settlement) or if you want to imply maneuvering to possess something (procure a reserved parking space). But beware: Procure is so often used to describe the act of obtaining partners to gratify the lust of others (to procure a prostitute) that it has acquired somewhat unsavory overtones. Gain also implies effort, usually in getting something advantageous or profitable (gain entry; gain victory). In a similar vein, secure underscores the difficulty involved in bringing something to pass and the desire to place it beyond danger (secure a permanent peace; secure a lifeline). Attain should be reserved for achieving a high goal or desirable result (if she attains the summit of Mt. Everest, she will secure for herself a place in mountaineering history).

* onto & on to
  The preposition onto written as one word (instead of on to) is recorded from the early 18th century and has been widely used ever since. In US English, it is the regular form, although it is not wholly accepted in British English. Nevertheless, it is important to maintain a distinction between the preposition onto or on to and the use of the adverb on followed by the preposition to: she climbed onto (sometimes on to) the roof, but let's go on to (never onto) the next chapter.

* naked, bald, bare, barren, nude
  Someone who isn't wearing any clothes is naked; this adjective is usually associated with revealing a part or all of the body (her naked shoulder; a naked man ran from the building). A naked person who appears in a painting or photograph is said to be nude, a euphemistic but more socially acceptable term referring to the unclothed human body (in fact, the piece of art itself is called "a nude"). Bare can describe the branches of a tree as well as human limbs; it implies the absence of the conventional or appropriate covering (a bare wooden floor; bare legs; four bare walls). Bald also suggests a lack of covering, but it refers particularly to a lack of natural covering, especially hair (a bald head). Barren implies a lack of vegetation, and it also connotes destitution and fruitlessness (a barren wasteland devoid of life). A bald artist might paint a nude woman whose bare arms are extended against a barren winter landscape.

* the reason why, the reason that, the reason ... is because, the reason ... is that
  The construction the reason why … has been objected to on the grounds that the subordinate clause should express a statement, using a that-clause, not imply a question with a why-clause: the reason (that) I decided not to phone, rather than the reason why I decided not to phone. The reason why has been called a redundancy to be avoided, but it is a mild one, and idiomatic.
  An objection is also made to the construction the reason … is because, as in the reason I didn't phone is because my mother has been ill. The objection is made on the grounds that either “because” or “the reason” is redundant; it is better to use the word that instead ( the reason I didn't phone is that …) or rephrase altogether ( I didn't phone because …).
  Nevertheless, both the above usages are well established and, although they may be inelegant, they are generally accepted in standard English.

* nauseous, nauseated
  A distinction has traditionally been drawn between nauseated, meaning ‘affected with nausea,’ and nauseous, meaning ‘causing nausea.’ Today, however, the use of nauseous to mean ‘affected with nausea’ is so common that it is generally considered to be standard.

* obsequious, servile, slavish, subservient
  If you want to get ahead with your boss, you might trying being obsequious, which suggests an attitude of inferiority that may or may not be genuine, but that is assumed in order to placate a superior in hopes of getting what one wants (a “goody two shoes” whose obsequious behavior made everyone in the class cringe). While subservient may connote similar behavior, it is more often applied to those who are genuinely subordinate or dependent and act accordingly (a timid, subservient child who was terrified of making a mistake). Servile is a stronger and more negative term, suggesting a cringing submissiveness (the dog's servile obedience to her master). Slavish, suggesting the status or attitude of a slave, is often used to describe strict adherence to a set of rules or a code of conduct (a slavish adherence to the rules of etiquette).

* stubborn, dogged, intractable, obdurate, obstinate, pertinacious
  If you're the kind of person who takes a stand and then refuses to back down, your friends might say you have a stubborn disposition, a word that implies an innate resistance to any attempt to change one's purpose, course, or opinion. People who are stubborn by nature exhibit this kind of behavior in most situations, but they might be obstinate in a particular instance (a stubborn child, he was obstinate in his refusal to eat vegetables). Obstinate implies sticking persistently to an opinion, purpose, or course of action, especially in the face of persuasion or attack. While obstinate is usually a negative term, dogged can be either positive or negative, implying both tenacious, often sullen, persistence (dogged pursuit of a college degree, even though he knew he would end up in the family business) and great determination (dogged loyalty to a cause). Obdurate usually connotes a stubborn resistance marked by harshness and lack of feeling (obdurate in ignoring their pleas), while intractable means stubborn in a headstrong sense and difficult for others to control or manage (intractable pain). No matter how stubborn you are, you probably don't want to be called pertinacious, which implies persistence to the point of being annoying or unreasonable (a pertinacious panhandler).

* relinquish, abandon, cede, surrender, waive, yield
  Of all these verbs meaning to let go or give up, relinquish is the most general. It can imply anything from simply releasing one's grasp (she relinquished the wheel) to giving up control or possession reluctantly (after the defeat, he was forced to relinquish his command). Surrender also implies giving up, but usually after a struggle or show of resistance (the villagers were forced to surrender to the guerrillas). Yield is a milder synonym for surrender, implying some concession, respect, or even affection on the part of the person who is surrendering (she yielded to her mother's wishes and stayed home). Waive means to give up voluntarily a right or claim to something (she waived her right to have a lawyer present), while cede is to give up by legal transfer or according to the terms of a treaty (the French ceded the territory that is now Louisiana). If one relinquishes something finally and completely, often because of weariness or discouragement, the correct word is abandon (they were told to abandon all hope of being rescued).

* humor, wit, satire, sarcasm, invective, irony, cynicism, sardonic
  HUMOR: motive/aim: discovery; province: human nature; method/means: observation; audience: the sympathetic
  WIT: motive/aim: throwing light; province: words & ideas; method/means: surprise; audience: the intelligent
  SATIRE: motive/aim: amendment; province: morals & manners; method/means: accentuation; audience: the self-satisfied
  SARCASM: motive/aim: inflicting pain; province: faults & foibles; method/means: inversion; audience: victim & bystander
  INVECTIVE: motive/aim: discredit; province: misconduct; method/means: direct statement; audience: the public
  IRONY: motive/aim: exclusiveness; province: statement of facts; method/means: mystification; audience: an inner circle
  CYNICISM: motive/aim: self-justification; province: morals; method/means: exposure of nakedness; audience: the respectable
  SARDONIC: motive/aim: self-relief; province: adversity; method/means: pessimism; audience: the self

* duty, customs, tariff, levy or excise?
  These are all words for taxes on goods. Excise is for goods sold within a country. Customs is for goods brought into a country. Tariffs are on goods going into or coming out of a country, often in order to protect industry from cheap imports. Duty is more general and can be a customs or excise tax. Levy is the most general of all and can be any sort of tax or charge.  

* anger, rage, fury, ire, wrath, resentment, indignation
  These nouns denote varying degrees of marked displeasure. Anger, the most general, is strong and often heated displeasure: shook her fist in anger; retorted in anger at the insult; tried to suppress his anger over the treatment he had received.
  Rage and fury imply intense, explosive, often destructive emotion: smashed the glass in a fit of rage; lashed out in fury at the lies her opponent had spread.
  Ire is a term for anger most frequently encountered in literature: "The best way to escape His ire / Is, not to seem too happy" (Robert Browning).
  Wrath applies especially to a powerful anger that seeks vengeance or punishment: "[He] was arrested and was spared the awful wrath of my pistol-whipping uncles" (Maya Angelou).
  Resentment refers to indignant smoldering anger generated by a sense of grievance: deep resentment among the workers that eventually led to a strike.
  Indignation is righteous anger at something wrongful, unjust, or evil: "public indignation about takeovers causing people to lose their jobs" (Allan Sloan).

* target, objective, goal
  A target is usually officially recorded in some way, for example by an employer or by a government committee. It is often specific, and in the form of figures, such as number of sales or examination passes, or a date. People often set their own objectives : these are things that they wish to achieve, often as part of a project or a talk they are giving. Goals are often long-term, and relate to people's life and career plans or the long-term plans of a company or organization.

* regard, consider, see, view, perceive
  regard or consider? 用regard还是consider？
  These two words have the same meaning, but they are used in different patterns and structures. In this meaning consider must be used with a complement or clause: you can consider sb/sth to be sth or consider sb/sth as sth , although very often the to be or as is left out. 上述两词意义相同，但用于不同的句型和结构。用于此义时，consider必须与补语或从句连用，可用consider sb/sth to be sth 或consider sb/sth as sth，不过to be或as常常省略不用：
  •
  He considers himself an expert. 他认为自己是专家。
  •
  They are considered a high-risk group. 他们被视为高风险群体。
  You can also consider that sb/sth is sth and again, the that can be left out. 用consider that sb/sth is sth亦可，that同样可以省略。 Regard is used in a narrower range of structures. The most frequent structure is regard sb/sth as sth ; the as cannot be left out. regard可用的句型结构较少，最常用的结构是regard sb/sth as sth，但as不可省略：
  •
  I regard him a close friend.
  You cannot 不可用：
  •
  regard sb/sth to be sth
  or 或
  •
  regard that sb/sth is sth
  However, regard (but not consider in this meaning) can also be used without a noun or adjective complement but with just an object and adverb (sb/sth is highly regarded) or adverbial phrase ( regard sb/sth with suspicion/jealousy/admiration) . 不过，regard亦可不与名词或形容词补语连用，只与宾语和副词（如sb/sth is highly regarded某人／某事受到高度评价）或副词短语（如regard sb/sth with suspicion/jealousy/admiration以怀疑／妒忌／赞赏的眼光看待某人／某事）连用，consider则不能这样用。
  ---
  PATTERNS AND COLLECTIONS
  ● to regard / consider / see / view / perceive sb / sth as sth
  ● to regard / consider / see / view / perceive sb / sth from a particular point of view
  ● to consider sb / sth to be sth
  ● to consider that...
  ● generally / usually regarded / considered / seen / viewed / perceived as sth
  ● to regard / consider / see / view / perceive sb / sth favourably / unfavourably

* perquisite, prerequisite
  Perquisite and prerequisite are sometimes confused. Perquisite usually means ‘an extra allowance or privilege’: he had all the perquisites of a movie star, including a stand-in. Prerequisite means ‘something required as a condition’: passing the examination was one of the prerequisites for a teaching position.  

* alleviate, abate, allay, assuage, mitigate, relieve, temper
  To alleviate is to make something easier to endure (to alleviate the pain following surgery); allay is often used interchangeably, but it also means to put to rest, to quiet or calm (to allay their suspicions). Assuage and allay both suggest the calming or satisfying of a desire or appetite, but assuage implies a more complete or permanent satisfaction (we allay our hunger by nibbling hors d'oeuvres, but a huge dinner assuages our appetite). To relieve implies reducing the misery or discomfort to the point where something is bearable (headphones help relieve the monotony of the cross-country bus trip), and mitigate, which comes from a Latin word meaning to soften, usually means to lessen in force or intensity (mitigate the storm's impact). Abate suggests a progressive lessening in degree or intensity (her fever was abating). To temper is to soften or moderate (to temper justice with mercy), but it can also mean the exact opposite: to harden or toughen something (tempering steel; a body tempered by lifting weights).

* admission, admittance
  Admission traditionally refers to the price paid for entry or the right to enter (admission was $5), and admittance more often refers to physical entry (we were denied admittance by a large man with a forbidding scowl). In the sense of 'permission or right to enter,' these words have become almost interchangeable, although admittance is more formal and technical.

* body, cadaver, carcass, corpse, cremains, remains
  The problem of what to call the human body after it has departed this life is a delicate one. Although a body can be either dead or alive, human or animal, a corpse is most definitely a dead human body and a carcass is the body of a dead animal. The issue has been confused, of course, by the figurative use of carcass as a term of contempt: get your carcass out of bed and come down here! While carcass is often used humorously, there's nothing funny about corpse, a no-nonsense term for a lifeless physical body (the battlefield was littered with corpses). A funeral director is likely to prefer the term remains, which is a euphemism for the body of the deceased (he had his wife's remains shipped home for burial), or cremains, if the body has been cremated. A medical student, on the other hand, is much more likely to use the term cadaver, which is a corpse that is dissected in a laboratory for scientific study.

* wince, cower, cringe, flinch, recoil
  The same individual might wince when receiving a flu shot, flinch from a difficult task, and cower in fear at the approach of a tornado. All of these verbs mean to draw back in alarm, disgust, faintheartedness, or servility, but there are subtle differences among them. To wince is to make a slight recoiling movement, often an involuntary contraction of the facial features, in response to pain or discomfort (to wince when the singer misses a high note), while flinch may imply a similar drawing-back motion or, more abstractly, a reluctance or avoidance (to tackle the job without flinching). Cower and cringe both refer to stooped postures, although cower is usually associated with fearful trembling (he cowered in the doorway) while cringe is usually linked to servile, cowardly, or fawning behavior (she cringed before her father's authority). More than any of the other verbs here, recoil suggests a physical movement away from something (recoil at the sight of a poisonous snake), although that movement may also be psychological (recoil at the very thought of a family reunion).

* Asiatic
  The standard and accepted term when referring to individual people is Asian rather than Asiatic, which can be offensive. However, Asiatic is standard in scientific and technical use, for example in biological and anthropological classifications. See also usage at oriental.

* despise, abhor, contemn, detest, disdain, loathe, scorn
  It's one thing to dislike someone; it's quite another to despise or detest the person. Both are strong words, used to describe extreme dislike or hatred. Detest is probably the purest expression of hatred (she detested the woman who had raised her, and longed to find her own mother), while despise suggests looking down with great contempt and regarding the person as mean, petty, weak, or worthless (he despised men whose only concern was their own safety). Disdain carries even stronger connotations of superiority, often combined with self-righteousness (to disdain anyone lacking a college education). Scorn is a stronger word for disdain, and it implies an attitude of not only contempt but of haughty rejection or refusal (to scorn the woman he'd once loved). To loathe something is to feel utter disgust toward it (he grew to loathe peanut butter and jelly sandwiches) and to abhor it is to feel a profound, shuddering, repugnance (she abhorred the very idea of asking her husband for the money). Contemn is a more literary word meaning to treat with disdain, scorn, or contempt.

* clarify, construe, elucidate, explain, explicate, interpret
  When a biology teacher gets up in front of a class and tries to explain how two brown-eyed parents can produce a blue-eyed child, the purpose is to make an entire process or sequence of events understandable. In a less formal sense, to explain is to make a verbal attempt to justify certain actions or to make them understood (she tried to explain why she was so late). That same teacher might clarify a particular exam question that almost everyone in the class got wrong—clarify being a word that means to make an earlier event, situation, or statement clear. Elucidate is a more formal word meaning to clarify, but where the root of the latter refers to clearness, the root of the former refers to light; to elucidate is to shed light on something through explanation, illustration, etc. (the principal's comments were an attempt to elucidate the school's policy on cheating). A teacher who explicates something discusses a complex subject in a point-by-point manner (to explicate a poem). If a personal judgment is inserted in making such an explication, the correct word is interpret (to interpret a poem's symbolic meanings). To construe is to make a careful interpretation of something, especially where the meaning is ambiguous. For example, when a class misbehaves in front of a visitor, the teacher is likely to construe that behavior as an attempt to cause embarrassment or ridicule.

* avenge, revenge
  1.
  Avenge is a verb; revenge is (usually) a noun. avenge为动词，revenge通常作名词。
  2.
  People avenge something or avenge themselves on somebody. 报某事之仇用avenge something，向某人报仇用avenge oneself on somebody：
  •
  She vowed to avenge her brother’s death. 她发誓要为哥哥之死报仇。
  •
  He later avenged himself on his wife’s killers. 他后来向杀害他妻子的人报了仇。
  You take revenge on a person. 报复某人用take revenge on。
  3.
  In more formal or literary English, revenge can also be a verb. People revenge themselves on somebody or are revenged on them (with the same meaning). 在较正式或文学用语中，revenge亦可作动词。revenge oneself on somebody或be revenged on somebody意思相同，均表示向某人报仇：
  •
  He was later revenged on his wife’s killers. 他后来向杀害他妻子的人报了仇。
  You cannot revenge something. 不能说revenge something：
  •
  She vowed to revenge her brother’s death.  

* comprise • make up • constitute • be composed of • be comprised of • compose
  All these words mean to be formed from the things or people mentioned, or to be the parts that form sth. 以上各词均表示由某些人或事物组成，或构成某事物。
  1. consist of sb/sth
  to be formed from the things, people or activities mentioned 指由事物、人或活动组成、构成：
  • Their diet consists largely of vegetables. 他们的日常饮食以蔬菜为主。
  2. comprise
  ( rather formal ) to be formed from the things or people mentioned 指由…组成、构成：
  •
  The collection comprises 327 paintings. 这部画册收有327幅画。
  NOTE Comprise can also be used to refer to the parts or members of sth. comprise亦可指组成、构成：
  •
  Older people comprise a large proportion of those living in poverty. 在那些生活贫困的人中，老年人占有很大的比例。
  However, this is less frequent. 不过这种用法不常见。
  3. make up sth
  ( rather informal ) to be the parts or people that form sth 指组成、构成：
  • Women make up 56% of the student numbers. 女生占学生人数的56%。
  4. constitute
  to be the parts or people that form sth 指组成、构成：
  • People under the age of 40 constitute the majority of the labour force. 40岁以下的人占劳动力的大多数。
  5. be composed of sb/sth
  ( rather formal ) to be formed from the things or people mentioned 指由…组成、构成：
  • Around 15% of our diet is composed of protein. 我们的饮食中大约有15%的蛋白质。
  6. be comprised of sb/sth
  to be formed from the things or people mentioned 指由…组成、构成：
  •
  The committee is comprised of representatives from both the public and private sectors. 委员会由政府和私人部门两方的代表组成。
  NOTE Some people consider this usage incorrect, and prefer to use the active verb comprise . 有人认为这种用法不正确，更喜欢用comprise的主动语态。
  7. compose
  ( formal ) to be the parts of people that form sth 指组成、构成：
  • Christians compose around 2.5% of the country's population. 基督教徒大约占这个国家人口的2.5%。
  which word? 词语辨析
  Consist of sb/sth is the most general of these words and the only one that can be used for activities with the -ing form of a verb. consist of是这组词中最通用、也是唯一可与动词-ing形式连用，表示包含…活动的词：
  •
  My work at that time just consisted of typing letters. 我那时的工作只有打信。
  The other main difference is between those verbs that take the whole as the subject and the parts as the object 另一个主要区别在于有些词是将整体作为主语，部分作为宾语：
  •
  The group consists of/comprises/is made up of/is composed of/is comprised of ten people. 这个小组由十个人组成。
  and those that take the parts as the subject and the whole as the object. 另一些词则是将部分作为主语，整体作为宾语：
  •
  Ten people make up/constitute/comprise/compose the group. 这个小组由十个人组成。
  It is not correct to use ‘comprises of’ or ‘is composed by/from’. 用comprise of或be composed by/from均不正确。

* clash • brawl • struggle • scuffle • tussle

  These are all words for a situation in which people try to defeat each other using physical force. 以上各词均指搏斗、打斗、打架。
  1. fight
  a situation in which two or more people try to defeat each other using physical force 指搏斗、打斗、打架：
  • He got into a fight with a man in the bar. 他在酒吧里和一个男人斗殴。
  2. clash
  ( journalism ) a short fight between two groups of people 新闻用语，指两群人之间短暂的打斗、打架、冲突：
  • Clashes broke out between police and demonstrators. 警方与示威者发生了冲突。
  3. brawl
  a noisy and violent fight involving a group of people, usually in a public place 通常指一群人在公共场合喧闹、斗殴、闹事：
  • a drunken brawl in a bar 在酒吧里酒后闹事
  4. struggle
  a fight between two people or groups of people, especially when one of them is trying to escape, or to get sth from the other 指搏斗、扭打，尤指抢夺、挣扎脱身：
  • There were no signs of a struggle at the murder scene. 在谋杀现场没有搏斗痕迹。
  5. scuffle
  a short and not very violent fight or struggle 指短暂而不太激烈的扭打、冲突：
  • He was involved in a scuffle with a photographer. 他和一名摄影记者发生了肢体冲撞。
  6. tussle
  a short struggle, fight or argument, especially in order to get sth 尤指为争夺物品的短时间的扭打、争斗、争执：
  • He was injured during a tussle for the ball. 他在争球时受了伤。
  PATTERNS AND COLLECTIONS
  
  ● in a fight / brawl / struggle / scuffle / tussle
  ● a fight / clash / brawl / struggle / scuffle / tussle over sth
  ● to be in / get into / be involved in a fight / clash / brawl / struggle / scuffle / tussle
  ● to start a fight / brawl / scuffle
  ● a fight / clash / brawl / struggle / scuffle / tussle breaks out
  ● a fight / clash / brawl / struggle / scuffle takes place / starts
  ● a violent fight / clash / brawl / struggle / scuffle / tussle
  ● a street fight / brawl

* crash • slam • collide • smash • wreck

  These are all words that can be used when sth, especially a vehicle, hits sth else very hard and is damaged or destroyed. 以上各词均含碰撞、撞击之义，尤指撞车。
  1. crash
  ( rather informal ) to hit an object or another vehicle, causing damage; to make a vehicle do this 指（使）物体或交通工具碰撞或撞击：
  • I was terrified that the plane would crash. 飞机会失事把我吓坏了。
  2. slam (sth) into/against sb/sth
  to crash into sth with a lot of force; to make sth do this 指（使）重重地撞上：
  • The car skidded and slammed into a tree. 汽车打滑，重重地撞到树上。
  3. collide
  ( rather formal ) (of two vehicles or people) to crash into each other; (of a vehicle or person) to crash into sb/sth else 指交通工具或人碰撞、相撞或撞上：
  • The car and the van collided head-on in thick fog. 那辆小轿车和货车在浓雾中迎面相撞。
  4. smash
  ( rather informal ) to crash into sth with a lot of force; to make sth do this; to crash a car 指（使）猛烈撞击、猛烈碰撞或撞车：
  • Ramraiders smashed a stolen car through the shop window. 飙车抢劫者驾着偷来的汽车撞破商店橱窗。
  crash, slam or smash? 用crash、slam还是smash？
  Crash is used particularly for vehicles and can be used without a preposition. crash尤指交通工具碰撞，可不与介词连用：
  •
  We're going to crash, aren't we? 我们要坠毁了，是不是？
  In this meaning slam and smash always take a preposition. slam和smash表示此义时总是与介词连用：
  •
  We're going to slam/smash, aren't we?
  They are used for a much wider range of things than just vehicles. Crash can also be used for other things, if used with a preposition. 两词均可用于除交通工具外的范围更广的事物。crash与介词连用也可用于其他事物：
  •
  He crashed down the telephone receiver. 他砰的一声将电话听筒摔下来。
  5. wreck
  to crash a vehicle and damage it so badly that it is not worth repairing 指使交通工具撞坏或毁坏
  PATTERNS AND COLLECTIONS
  
  ● The two vehicles crashed / collided.
  ● The two vehicles crashed / slammed / smashed into each other .
  ● The car / plane crashed / slammed / smashed into a tree.
  ● I've crashed / smashed / wrecked the car .
  ● to crash / slam / collide / smash head-on (into / with sth)

* statement • account • invoice • tab • check

  These are all words for a record of how much you owe for goods or services you have bought or used. 以上各词均指账单、账目。
  1. bill
  a list of goods that you have bought or services that you have used, showing how much you owe; the price or cost of sth 指账单：
  • the gas bill 煤气费账单
  2. statement
  a printed record of money spent, received, etc. 指结算单、清单、报表：
  •
  the company's annual financial statement 公司的年度财务报表
  •
  a bank statement (= a record of money paid into and out of a bank account) 银行结单
  •
  a credit card statement 信用卡结单
  3. account
  an arrangement with a shop/store or business to pay bills for goods or services at a later time, for example in regular amounts every month 指赊销账、赊欠账、赊购：
  •
  Put it on my account please. 请记在我的赊购账上。
  NOTE In British English this can also be called a credit account . In North American English it can be called a charge account . 在英国英语中，此义亦可用credit account；北美英语可用charge account。
  4. invoice
  ( rather formal ) a bill for goods that sb has bought or work that has been done for sb 指发票、发货或服务费用清单：
  • The builders sent an invoice for ￡250. 营造商发出了一张250英镑的发票。
  bill or invoice? 用bill还是invoice？
  You would get a bill in a restaurant, bar or hotel; from a company that supplies you with gas, electricity, etc.; or from sb whose property you have damaged. An invoice is for goods supplied or work done as agreed between a customer and supplier, and is usually sent after the goods have been delivered or the work finished. bill指餐馆、酒吧、旅馆、煤气公司、电力公司等开出的账单或财产所有者开出的索赔清单。invoice指发票、发货费用清单或经客户与供应商约定的服务费用清单，一般于交货或完工后发出。
  5. tab
  ( rather informal ) a bill for goods you receive but pay for later, especially for food or drinks in a restaurant or bar; the price or cost of sth 指待付的账单、账款、费用，尤指餐厅或酒吧账单：
  •
  a bar tab 酒吧账单
  •
  Can I put it on my tab? 我可以记账吗？
  6. check
  ( NAmE ) a piece of paper that shows how much you have to pay for the food and drinks that you have had in a restaurant 指餐馆的账单：
  •
  Can I have the check, please? 请把账单给我好吗？
  NOTE In British English the usual word for this is bill . 此义英国英语常用bill。
  PATTERNS AND COLLECTIONS
  
  ● the bill / invoice / tab / check for sth
  ● to pay / settle a(n) bill / account / invoice / tab / check
  ● to pick up (= pay) the bill / tab / check
  ● to put sth on the / sb's bill / account / invoice / tab / check
  ● to send / submit a(n) bill / invoice to a customer
  ● to ask for / get the bill / check (= especially in a restaurant or bar)
  ● She asked the waiter if she could have the bill / check.

* mark • stain • streak • speck • blot • smear • spot

  These are all words for a small area of dirt or another substance on a surface. 以上各词均指污点、斑点、污迹。
  1. mark
  a small area of dirt or other substance on the surface of sth, especially one that spoils its appearance 指污点、污迹、斑点：
  • The kids left dirty marks all over the kitchen floor. 孩子们把厨房的地板弄得污迹斑斑。
  2. stain
  a dirty mark on sth that is difficult to remove, especially one made by a liquid 指污点、污渍：
  • blood stains 血迹
  3. streak
  a long thin mark or line that is a different colour from the surface it is on 指条纹、条痕：
  • She had streaks of grey in her hair. 她头上已是白发绺绺。
  4. speck
  a very small mark, spot or piece of a substance on sth 指小点、污点：
  • There isn't a speck of dust anywhere in the house. 整间房子一尘不染。
  5. blot
  a spot or dirty mark left on sth by a substance such as ink or paint being dropped on a surface 指污点、墨渍
  6. smear
  a mark made by sth such as oil or paint being spread or rubbed on a surface 指污迹、油渍、污渍、污点
  7. spot
  a small dirty mark on sth 指污迹、污渍、污点：
  • There were grease spots all over the walls. 四周的墙上满是油渍。
  PATTERNS AND COLLECTIONS
  
  ● a streak / speck / blot / smear / spot of sth
  ● a dirty mark / stain / streak / speck / smear / spot
  ● an ink mark / stain / blot / spot
  ● a(n) oil / grease / paint mark / stain / spot
  ● to leave a mark / stain / streak / speck / blot / smear / spot
  ● to get a mark / stain / spot out of sth
